import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="min-h-full" >
      <body suppressHydrationWarning={true} className="h-screen p-5">{children}</body>
    </html>
  );
}
